nohup: ignoring input
Traceback (most recent call last):
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/hubs/hub.py", line 471, in fire_timers
    timer()
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/greenthread.py", line 265, in main
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/socketio/server.py", line 589, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/socketio/server.py", line 614, in _trigger_event
    return handler(*args)
           ^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 293, in _handler
    return self._handle_event(handler, message, real_ns, sid,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 838, in _handle_event
    ret = handler(*args)
          ^^^^^^^^^^^^^^
  File "/home/theone/connect4-web2/app.py", line 53, in handle_make_move
    player = data['player']
             ~~~~^^^^^^^^^^
KeyError: 'player'
Traceback (most recent call last):
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/hubs/hub.py", line 471, in fire_timers
    timer()
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/greenthread.py", line 265, in main
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/socketio/server.py", line 589, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/socketio/server.py", line 614, in _trigger_event
    return handler(*args)
           ^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 293, in _handler
    return self._handle_event(handler, message, real_ns, sid,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 838, in _handle_event
    ret = handler(*args)
          ^^^^^^^^^^^^^^
  File "/home/theone/connect4-web2/app.py", line 53, in handle_make_move
    player = data['player']
             ~~~~^^^^^^^^^^
KeyError: 'player'
Traceback (most recent call last):
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/hubs/hub.py", line 471, in fire_timers
    timer()
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/greenthread.py", line 265, in main
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/socketio/server.py", line 589, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/socketio/server.py", line 614, in _trigger_event
    return handler(*args)
           ^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 293, in _handler
    return self._handle_event(handler, message, real_ns, sid,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 838, in _handle_event
    ret = handler(*args)
          ^^^^^^^^^^^^^^
  File "/home/theone/connect4-web2/app.py", line 53, in handle_make_move
    player = data['player']
             ~~~~^^^^^^^^^^
KeyError: 'player'
Traceback (most recent call last):
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/hubs/hub.py", line 471, in fire_timers
    timer()
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/home/theone/.local/lib/python3.12/site-packages/eventlet/greenthread.py", line 265, in main
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/socketio/server.py", line 589, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/socketio/server.py", line 614, in _trigger_event
    return handler(*args)
           ^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 293, in _handler
    return self._handle_event(handler, message, real_ns, sid,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theone/.local/lib/python3.12/site-packages/flask_socketio/__init__.py", line 838, in _handle_event
    ret = handler(*args)
          ^^^^^^^^^^^^^^
  File "/home/theone/connect4-web2/app.py", line 53, in handle_make_move
    player = data['player']
             ~~~~^^^^^^^^^^
KeyError: 'player'
